project:
  type: "website"

website:
  title: "test-quarto-link-issue"
  navbar:
    left:
      - text: "Home"
        href: "index.qmd"

format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
